## <center> Lecture 5 </center>
## <center> Dictionaries and Sets </center>

## Dictionaries
* Dictionaries are a popular data structure in Python
* Dictionaries hold _unordered_, _key-value_ pairs
* Why are they called "dictionaries"?

* Consider a conventional dictionary, and let's look up a common word: <br> <br>
_Loquacious_: tending to talk a great deal; talkative.

* In the above, "Loquacious" is the queried word, and "tending to talk a great deal; talkative" is the returned meaning

* Dictionaries in Python work the same way!

# Demonstrating a simple dictionary
* Let's create a dictionary to store our favorite irrational numbers:

In [10]:
my_first_dictionary = {'pi': 3.1416, 'exp': 2.7183}

* Now let's retrieve these numbers:

In [12]:
my_first_dictionary['pi']

3.1416

In [13]:
my_first_dictionary['exp']

2.7183

* The brace brackets ```{}``` tell Python that we are creating a dictionary
* The strings ```'pi'``` and ```'exp'``` are called _keys_
* The floats ```3.1416``` and ```2.7183``` are the corresponding _values_
* Note that we access dictionary values using ```[]```, just like a list!

## Dictionary rules
* Keys must be immutable: strings, integers, tuples
* Keys must be unique
* Here are two valid dictionaries:

In [14]:
dd = {1:'one', 2:'two', 3:'three'}

In [20]:
dd[2]

'two'

In [15]:
ddd = {(2,3,5,7,9): 'prime', (1,4,6,8,10): 'non-prime'}

In [19]:
ddd[(2,3,5,7,9)]

'prime'

## The order of the items is not preserved in Python
* Dictionary elements are unordered
* Two keys can map to the same value:

In [21]:
dddd = {'Loquacious': 'Boss', 'Jacek': 'Boss'}

In [23]:
dddd['Loquacious']==dddd['Jacek']

True

## Dictionaries can be empty
* ```dd={}``` creates an empty dictionary
* We can then add items to the dictionary:

In [39]:
dd={}
dd['one'] = 1
dd['two'] = 2
dd

{'one': 1, 'two': 2}

* ```dd.clear()``` removes all elements of a dictionary

In [40]:
dd.clear()
dd

{}

## Iterating through a dictionary
* The keyword ```items()``` allows you to iterate through all elements of a dictionary

In [112]:
dd = {'one': 1, 'two': 2, 'three':3}
for key, val in dd.items():
    print(key, ':', val)

one : 1
two : 2
three : 3


* Notice above that ```items()``` returns a _tuple_
* The first element of the tuple is the key, the second is the value

## Adding dictionary values
* Adding new elements to a dictionary is straightforward
* Let's define a dictionary mapping American presidents to their presidential order

In [116]:
presidents = {'Washington': 1, 'Lincoln': 16, 'Obama': 44, 'Trump': 45}

* Let's add the current president:

In [117]:
presidents['Biden']=46
presidents

{'Washington': 1, 'Lincoln': 16, 'Obama': 44, 'Trump': 45, 'Biden': 46}

## Dictionary values can be overwritten
* It is sometimes desirable to modify the value of a key-value pair
* Let's randomly modify one of the values in our ```presidents``` dictionary:

In [118]:
presidents['Trump']=[45,47]
presidents

{'Washington': 1, 'Lincoln': 16, 'Obama': 44, 'Trump': [45, 47], 'Biden': 46}

* Notice that we've changed the type of ```presidents['Trump']``` from an integer to a list

## Dictionary elements can be removed
* The ```pop()``` method allows you to remove a key-value pair from your dictionary

In [119]:
presidents.pop('Trump') 
presidents

{'Washington': 1, 'Lincoln': 16, 'Obama': 44, 'Biden': 46}

## Checking whether a key exists with ```get()```
* The ```get()``` method returns ```None``` if a key is non-existent

In [120]:
print(presidents.get('Lincoln'))

16


In [121]:
print(presidents.get('Gore'))

None


## Checking whether a key exists with ```in```
* A more common way of checking for the existence of a key is with the ```in``` keyword:

In [122]:
candidates = ['Gore', 'Washington', 'Trump']

for c in candidates:
    if c in presidents:
        print(c, "was president number", presidents[c])
    else:
        print(c, "was not a president")

Gore was not a president
Washington was president number 1
Trump was not a president


* Make sure that you understand the logic and syntax inside the for loop body above

## Iterating through a dictionary's keys
* Sometimes we only need to iterate through a dictionary's keys
* This is accomplished with the ```keys()``` method:

In [123]:
for p in presidents.keys():
    print(p, 'was a president')

Washington was a president
Lincoln was a president
Obama was a president
Biden was a president


* We may also iterate through a dictionary's _values_ via the method ```values()```

In [124]:
for v in presidents.values():
    print(v)

1
16
44
46


## Dictionary comprehensions
* Dictionaries do not always have to generated manually!
* _Dictionary comprehensions_ are a powerful feature for dynamically populating dictionaries
* The syntax is analogous to what you saw for _list_ comprehensions

## Creating a dictionary of the perfect squares
* To demonstrate dictionary comprehensions, let's create a dictionary mapping integers to their squared value:

In [126]:
dd = {number: number**2 for number in range(10)}

* Let's inspect the dictionary:

In [127]:
dd

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

```number: number**2``` is the formula defining each dictionary element

```for number in range(10)``` tells Python which elements to include in our dictionary

* Let's recreate the dictionary but with _string_ keys:

In [128]:
dd = {str(number): number**2 for number in range(10)}

In [129]:
dd

{'0': 0,
 '1': 1,
 '2': 4,
 '3': 9,
 '4': 16,
 '5': 25,
 '6': 36,
 '7': 49,
 '8': 64,
 '9': 81}

* Notice that the keys now have string type

## Sets
* Sets are unordered values: like dictionaries, but without the keys
* They are used less often than dictionaries, but are sometimes more appropriate
* The syntax is consistent to that of dictionaries:

In [130]:
presidents = {'Washington', 'Lincoln', 'Obama', 'Biden'}
presidents

{'Biden', 'Lincoln', 'Obama', 'Washington'}

## Determining the number of items in your set
* ```len``` tells you the number of elements in your set:

In [78]:
len(presidents)

4

* ```in``` tells you whether an element is in a set:

In [79]:
'Obama' in presidents

True

## Iterating through a set
* We iterate through sets in the same way as we did for dictionaries:

In [131]:
for p in presidents:
    print(p, "was a president")

Obama was a president
Biden was a president
Lincoln was a president
Washington was a president


## Checking for subsets
* A is said to be a _subset_ of B if every element of A is also in B
* Python offers multiple ways for determining subset relations
* Let's first create two sets:

In [132]:
primes = {2,3,5,7} 
integers = set(range(9))
print('The prime numbers are:', primes)
print('The integers are:', integers)

The prime numbers are: {2, 3, 5, 7}
The integers are: {0, 1, 2, 3, 4, 5, 6, 7, 8}


* Notice that ```set(range(9))``` casts ```range(9)``` to a ```set``` type:

In [133]:
type(integers) 

set

In [134]:
if primes < integers:
    print('The primes are a subset of the integers')
else:
    print('The primes are not a subset of the integers')

The primes are a subset of the integers


In [135]:
if primes.issubset(integers):
    print('The primes are a subset of the integers')
else:
    print('The primes are not a subset of the integers')

The primes are a subset of the integers


## Set operations
* It is commonly required to combine two sets
* The _union_ of set A and set B is a set containing all elements that are in A _or_ B
* The ```union()``` method implements this operation to produce a new, combined set: 

In [136]:
evens = {2,4,6,8,10}
odds = {1,3,5,7,9}
integers = evens.union(odds)
print("The integers are:", integers)

The integers are: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


* We can also call the method ```union()``` on the ```odds``` object:

In [99]:
integers = odds.union(evens)
print("The integers are:", integers)

The integers are: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


## The ```intersection()``` outputs all elements that are in _both_ input sets:

In [137]:
evens = {2,4,6,8,10}
primes = {2,3,5,7}
print('The even prime numbers are:', evens.intersection(primes))

The even prime numbers are: {2}


## The ```difference()``` outputs all elements that are in one set but not the second:

In [138]:
evens = {2,4,6,8,10}
primes = {2,3,5,7}
print('The difference between evens and primes is:', evens.difference(primes))

The difference between evens and primes is: {8, 10, 4, 6}


* Notice that sets are unordered!
* You can verify this with the ```==``` operator:

In [139]:
{4,6,8,10} == {8,10,4,6}

True

## Adding and removing set elements
* The functions ```add()``` and ```remove``` allow you to add and remove elements to sets:

In [140]:
primes={2,3,5,7}
primes.add(9)
primes.add(11)
primes

{2, 3, 5, 7, 9, 11}

In [141]:
primes.remove(11)
primes

{2, 3, 5, 7, 9}

## Set comprehensions
* Sets can be created dynamically with _set comprehension_:

In [142]:
evens = {number for number in range(1,11) if (number%2)==0}

In [143]:
evens

{2, 4, 6, 8, 10}

* ```number``` specifies the identity of each set element
* The iterable ```for number in range(1,11)``` tells Python which numbers to add to our dynamic set
* The conditional ```if (number%2)==0``` tells Python to exclude any number that divides evenly into 2 